### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by burf2000** [ddemidov/ev3dev-lang-python#17]
I have installed the latest EV3Dev
I have followed your instructions

I get

>>> import ev3dev
>>> m = ev3dev.LargeMotor('outA')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'LargeMotor'
>>>

**Comment by ddemidov** [comment]
The master branch is currently in the process of merging interface with @rhempel's [pure-python](https://github.com/ev3dev/ev3dev-lang/tree/pure-python/pure-python) bindings. Specifically, the names of the classes have been changed recently, but the changes have not yet been pushed to pypi.

As a result, you would need to you instructions either from https://github.com/ddemidov/ev3dev-lang-python/tree/cd471e03973ec640bce27b1d3d05d827ab8b0a4b, or from the [reference documentation](http://ddemidov.github.io/ev3dev-lang-python/).

Sorry for the inconvenience.

**Comment by ddemidov** [comment]
I've reverted the master branch to the published version and moved the unpublished changes to develop. Thanks for reporting this!

**Comment by burf2000** [comment]
So just follow the instructions again and it should work?

**Comment by burf2000** [comment]
Running your demo code for motor I get
  File "test.py", line 17, in <module>
    Motor(OUTPUT_A),
NameError: name 'Motor' is not defined

**Comment by ddemidov** [comment]
> So just follow the instructions again and it should work?

Yes, but note that the code you cited now looks like
```
>>> import ev3dev
>>> m = ev3dev.large_motor('outA')
```

**Comment by burf2000** [comment]
Seems to work now, can I just ask how I would get non EV3 motors to work (PF Motors)

**Comment by ddemidov** [comment]
The ev3dev documentation on power function motors (http://www.ev3dev.org/docs/drivers/rcx-motor/) seems to suggest you need a `dc_motor` class to work with them. Have a look at http://www.ev3dev.org/docs/drivers/dc-motor-class/ and http://ddemidov.github.io/ev3dev-lang-python/#ev3dev.dc_motor.

**Comment by rhempel** [comment]
Denis,

I'm happy to use whatever format we settle on as long as it's Pythonic and meets PEP 008. If you want me to update the binding generator to make classes that look more like your code here:

<http://ddemidov.github.io/ev3dev-lang-python/#ev3dev.dc_motor>

then we can do that too. Which standard should we settle on to minimize breakage :-)

**Comment by gitjoost** [comment]
Neither
>>> import ev3dev
>>> m = ev3dev.large_motor('outA')

Nor
>>> import ev3dev
>>> m = ev3dev.LargeMotor('outA')

is working for me. Both give the same error: AttributeError: 'module' object has no attribute 'large_motor'  (or 'LargeMotor').   Note that the module imports fine, installation lists python_ev3dev-0.6.0 is installed.

**Comment by ddemidov** [comment]
That's because the repo is [no longer supported](https://github.com/ddemidov/ev3dev-lang-python). Have a look at https://github.com/rhempel/ev3dev-lang-python instead.
